"""
Behavior Engine Service for Arxos SVGX Engine

Handles behavior profile validation, creation, and management for the pipeline integration.
"""

import json
import os
from pathlib import Path
from typing import Dict, Any, List, Optional
import logging

from svgx_engine.utils.errors import BehaviorError, ValidationError

logger = logging.getLogger(__name__)


class BehaviorEngine:
    """Manages behavior profiles for the pipeline integration."""
    
    def __init__(self, behavior_path: str = "svgx_engine/behavior"):
        self.behavior_path = Path(behavior_path)
        self.behavior_path.mkdir(parents=True, exist_ok=True)
        
    def validate_system_behavior(self, system: str) -> Dict[str, Any]:
        """Validate behavior profiles for a system."""
        try:
            # Check if behavior file exists
            behavior_file = self.behavior_path / f"{system}.py"
            
            if not behavior_file.exists():
                return {
                    "valid": False,
                    "error": f"Behavior file not found: {behavior_file}",
                    "suggestion": "Run implement-behavior step first"
                }
            
            # Basic validation - check if file is valid Python
            try:
                with open(behavior_file, 'r') as f:
                    content = f.read()
                
                # Simple syntax check
                compile(content, behavior_file, 'exec')
                
                return {
                    "valid": True,
                    "message": f"Behavior validation passed for system: {system}",
                    "behavior_file": str(behavior_file),
                    "file_size": len(content)
                }
                
            except SyntaxError as e:
                return {
                    "valid": False,
                    "error": f"Invalid Python syntax: {str(e)}",
                    "behavior_file": str(behavior_file)
                }
                
        except Exception as e:
            raise BehaviorError(f"Behavior validation failed: {str(e)}", system)
    
    def create_system_behavior(self, system: str) -> Path:
        """Create a behavior profile for a system."""
        try:
            behavior_file = self.behavior_path / f"{system}.py"
            
            # Create basic behavior profile
            behavior_content = self._create_basic_behavior(system)
            
            with open(behavior_file, 'w') as f:
                f.write(behavior_content)
            
            logger.info(f"Created behavior profile: {behavior_file}")
            return behavior_file
            
        except Exception as e:
            raise BehaviorError(f"Failed to create behavior profile: {str(e)}", system)
    
    def _create_basic_behavior(self, system: str) -> str:
        """Create basic behavior profile content for a system."""
        return f'''"""
Behavior Profile for {system} System

This file contains the behavior definitions for the {system} system.
Generated by the Arxos pipeline integration.
"""

from typing import Dict, Any, List, Optional
import logging

logger = logging.getLogger(__name__)


class {system.title()}Behavior:
    """Behavior profile for {system} system objects."""
    
    def __init__(self):
        self.system = "{system}"
        self.behavior_version = "1.0"
        self.supported_objects = []
    
    def validate_object(self, object_data: Dict[str, Any]) -> Dict[str, Any]:
        """Validate an object in this system."""
        try:
            # Basic validation
            required_fields = ["id", "type", "position"]
            for field in required_fields:
                if field not in object_data:
                    return {{
                        "valid": False,
                        "error": f"Missing required field: {{field}}"
                    }}
            
            return {{
                "valid": True,
                "message": f"Object validation passed for {{system}} system"
            }}
            
        except Exception as e:
            return {{
                "valid": False,
                "error": f"Object validation failed: {{str(e)}}"
            }}
    
    def simulate_behavior(self, object_data: Dict[str, Any], simulation_params: Dict[str, Any]) -> Dict[str, Any]:
        """Simulate behavior for an object in this system."""
        try:
            # Basic simulation
            simulation_result = {{
                "object_id": object_data.get("id"),
                "system": self.system,
                "simulation_status": "completed",
                "results": {{
                    "status": "normal",
                    "performance": "optimal",
                    "alerts": []
                }}
            }}
            
            return simulation_result
            
        except Exception as e:
            return {{
                "object_id": object_data.get("id"),
                "system": self.system,
                "simulation_status": "failed",
                "error": str(e)
            }}
    
    def check_constraints(self, object_data: Dict[str, Any]) -> Dict[str, Any]:
        """Check constraints for an object in this system."""
        try:
            # Basic constraint checking
            constraints = {{
                "valid": True,
                "constraints_checked": [],
                "violations": []
            }}
            
            return constraints
            
        except Exception as e:
            return {{
                "valid": False,
                "error": f"Constraint checking failed: {{str(e)}}"
            }}
    
    def get_behavior_properties(self) -> Dict[str, Any]:
        """Get behavior properties for this system."""
        return {{
            "system": self.system,
            "version": self.behavior_version,
            "supported_objects": self.supported_objects,
            "capabilities": [
                "validation",
                "simulation", 
                "constraint_checking"
            ]
        }}


# Factory function for creating behavior instances
def create_{system}_behavior() -> {system.title()}Behavior:
    """Create a new {system} behavior instance."""
    return {system.title()}Behavior()


# Global behavior instance
{system}_behavior = create_{system}_behavior()
'''
    
    def get_behavior_properties(self, system: str) -> Dict[str, Any]:
        """Get behavior properties for a system."""
        try:
            behavior_file = self.behavior_path / f"{system}.py"
            
            if not behavior_file.exists():
                return {
                    "error": f"Behavior file not found: {behavior_file}"
                }
            
            # Import the behavior module
            import importlib.util
            spec = importlib.util.spec_from_file_location(f"{system}_behavior", behavior_file)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            
            # Get behavior instance
            behavior_instance = getattr(module, f"{system}_behavior", None)
            if behavior_instance:
                return behavior_instance.get_behavior_properties()
            else:
                return {
                    "error": f"Behavior instance not found in {behavior_file}"
                }
                
        except Exception as e:
            return {
                "error": f"Failed to get behavior properties: {str(e)}"
            }
    
    def list_behavior_systems(self) -> List[str]:
        """List all systems with behavior profiles."""
        systems = []
        
        try:
            for behavior_file in self.behavior_path.glob("*.py"):
                if behavior_file.name != "__init__.py":
                    system_name = behavior_file.stem
                    systems.append(system_name)
        
        except Exception as e:
            logger.error(f"Failed to list behavior systems: {str(e)}")
        
        return systems 