# ArxOS golangci-lint configuration
# Enhanced linting for production-ready code

run:
  # Timeout for analysis
  timeout: 5m

  # Exit code when issues are found
  issues-exit-code: 1

  # Include test files
  tests: true

  # List of build tags
  build-tags:
    - integration
    - load
    - chaos

  # Skip directories
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - docs

  # Skip files
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

  # Modules download mode
  modules-download-mode: readonly

output:
  # Output format
  format: colored-line-number

  # Print issued lines
  print-issued-lines: true

  # Print linter name
  print-linter-name: true

  # Unique issues
  uniq-by-line: true

  # Sort results
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type checking
    - unused        # Find unused code

    # Additional linters for code quality
    - bodyclose     # Check HTTP response body is closed
    - contextcheck  # Check context usage
    - dupl          # Code duplication
    - exportloopref # Check loop variable exports
    - gocognit      # Cognitive complexity
    - goconst       # Find repeated strings
    - gocritic      # Opinionated linter
    - gocyclo       # Cyclomatic complexity
    - gofmt         # Formatting
    - goimports     # Import organization
    - gomnd         # Magic numbers
    - goprintffuncname # Printf-like function naming
    - gosec         # Security issues
    - lll           # Line length limit
    - misspell      # Spelling mistakes
    - nakedret      # Naked returns
    - noctx         # HTTP requests without context
    - nolintlint    # Nolint directives
    - prealloc      # Slice preallocation
    - predeclared   # Shadowing predeclared identifiers
    - revive        # Fast, configurable linter
    - rowserrcheck  # SQL rows.Err() checking
    - sqlclosecheck # SQL rows/statements closing
    - stylecheck    # Style checker
    - thelper       # Test helpers
    - tparallel     # Test parallelization
    - unconvert     # Unnecessary conversions
    - unparam       # Unused parameters
    - whitespace    # Whitespace issues

    # Performance
    - gomodguard    # Module usage restrictions
    - importas      # Import aliasing

  disable:
    - depguard      # Too restrictive for imports
    - exhaustive    # Too strict for switches
    - gochecknoglobals # We use some globals
    - gochecknoinits   # We use init functions
    - godot         # Punctuation in comments
    - godox         # TODO/FIXME comments
    - goerr113      # Too strict error handling
    - golint        # Deprecated
    - interfacer    # Deprecated
    - maligned      # Deprecated
    - scopelint     # Deprecated
    - wrapcheck     # Too strict for error wrapping
    - wsl           # Whitespace linter too strict

linters-settings:
  # errcheck
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io.Copy
      - io.Pipe

  # govet
  govet:
    check-shadowing: true
    enable-all: true

  # gocyclo
  gocyclo:
    min-complexity: 15

  # gocognit
  gocognit:
    min-complexity: 20

  # dupl
  dupl:
    threshold: 150

  # goconst
  goconst:
    min-len: 3
    min-occurrences: 3

  # misspell
  misspell:
    locale: US

  # lll
  lll:
    line-length: 120
    tab-width: 4

  # unused
  unused:
    check-exported: false

  # unparam
  unparam:
    check-exported: false

  # nakedret
  nakedret:
    max-func-lines: 30

  # prealloc
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  # gocritic
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  # gosec
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104  # Unhandled errors (handled by errcheck)
      - G304  # File path provided as argument
    config:
      G101:   # Hard-coded credentials
        pattern: "(?i)passwd|pass|password|pwd|secret|token|apikey|api_key"

  # gomnd
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
          - assign
        ignored-numbers:
          - '0'
          - '1'
          - '2'
          - '10'
          - '100'
          - '1000'
        ignored-functions:
          - 'strconv.ParseInt'
          - 'strconv.ParseUint'
          - 'strconv.ParseFloat'

  # revive
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  # stylecheck
  stylecheck:
    go: "1.21"
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
    dot-import-whitelist:
      - fmt
    initialisms:
      - "ACL"
      - "API"
      - "ASCII"
      - "CPU"
      - "CSS"
      - "DNS"
      - "EOF"
      - "GUID"
      - "HTML"
      - "HTTP"
      - "HTTPS"
      - "ID"
      - "IP"
      - "JSON"
      - "LHS"
      - "QPS"
      - "RAM"
      - "RHS"
      - "RPC"
      - "SLA"
      - "SMTP"
      - "SQL"
      - "SSH"
      - "TCP"
      - "TLS"
      - "TTL"
      - "UDP"
      - "UI"
      - "UID"
      - "UUID"
      - "URI"
      - "URL"
      - "UTF8"
      - "VM"
      - "XML"
      - "XMPP"
      - "XSRF"
      - "XSS"
      - "HVAC"
      - "BIM"
      - "PLY"
      - "LIDAR"

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with same text
  max-same-issues: 10

  # Show only new issues created after git revision
  new: false

  # Fix found issues (if supported by linter)
  fix: false

  exclude-rules:
    # Exclude some linters from test files
    - path: _test\.go
      linters:
        - dupl
        - gomnd
        - goconst
        - gosec
        - noctx

    # Exclude some linters from integration tests
    - path: integration_test\.go
      linters:
        - dupl
        - gomnd
        - goconst

    # Exclude some linters from generated files
    - path: \.gen\.go
      linters:
        - gosec
        - dupl
        - lll
        - stylecheck

    # Exclude some linters from scripts
    - path: scripts/
      linters:
        - gosec

    # Exclude known issues in vendor
    - path: vendor/
      linters:
        - all

  exclude-use-default: false

  exclude:
    # Exclude common false positives
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
    - "exported (type|method|function) (.+) should have comment or be unexported"
    - "ST1000: at least one file in a package should have a package comment"
    - "should have a package comment, unless it's in another file for this package"

severity:
  default-severity: warning
  case-sensitive: false

  rules:
    - linters:
        - gosec
      severity: error

    - linters:
        - dupl
      severity: info

    - linters:
        - goconst
        - gomnd
      severity: info