# golangci-lint configuration for ArxOS
# This configuration enforces modern Go practices and prevents interface{} usage

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-line: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  # Prevent interface{} usage
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # Allow duplicate imports in some cases
    enabled-checks:
      - regexpMust
      - singleCaseSwitch
      - sloppyReassign
      - stringXbytes
      - unnecessaryBlock
      - unnecessaryDefer
      - unnecessaryGuard
      - wrapperFunc
      - whyNoLint
      - writeQuotedString
      - yodaStyleExpr
      - yodaStyleExpr2
    settings:
      gocritic:
        # Custom rules for interface{} detection
        disabled-checks:
          - dupImport
        enabled-checks:
          - regexpMust
          - singleCaseSwitch
          - sloppyReassign
          - stringXbytes
          - unnecessaryBlock
          - unnecessaryDefer
          - unnecessaryGuard
          - wrapperFunc
          - whyNoLint
          - writeQuotedString
          - yodaStyleExpr
          - yodaStyleExpr2

  # Enforce modern Go practices
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/arx-os/arxos

  govet:
    check-shadowing: true
    enable:
      - atomicalign
      - deepequalerrors
      - findcall
      - nilness
      - reflectvaluecompare
      - shadow
      - sortslice
      - unusedwrite
    disable:
      - fieldalignment # Can be too strict for some use cases

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 2
    min-occurrences: 2

  gocognit:
    min-complexity: 20

  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G204 # Subprocess launching should be audited
      - G304 # File path provided as taint input

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  revive:
    min-confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

  unused:
    check-exported: false

  whitespace:
    multi-if: false
    multi-func: false

  # Custom linter for interface{} detection
  custom:
    interface-check:
      path: ./scripts/lint-interface.sh
      description: "Detects usage of interface{} instead of any"
      original: true

linters:
  enable:
    # Core linters
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unused
    - gosimple
    - staticcheck
    - typecheck

    # Style and complexity
    - gocritic
    - gocyclo
    - goconst
    - gocognit
    - nakedret
    - prealloc
    - revive
    - whitespace

    # Security
    - gosec

    # Performance
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck

    # Custom linters
    - interface-check

  disable:
    - deadcode # Deprecated, use staticcheck
    - varcheck # Deprecated, use staticcheck
    - structcheck # Deprecated, use staticcheck
    - maligned # Deprecated, use govet fieldalignment
    - scopelint # Deprecated, use exportloopref
    - interfacer # Deprecated
    - golint # Deprecated, use revive

issues:
  # Don't skip any issues
  exclude-rules:
    # Allow some specific patterns
    - path: _test\.go
      linters:
        - gomnd # Allow magic numbers in tests
        - goconst # Allow repeated strings in tests

    # Allow some patterns in generated code
    - path: ".*\\.pb\\.go"
      linters:
        - gocritic
        - revive

    # Allow some patterns in vendor directory
    - path: vendor/
      linters:
        - gocritic
        - revive
        - gosec

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show only new issues
  new: false

  # Show only new issues created after git revision `rev`
  new-from-rev: ""

  # Show only new issues created in git patch with set file extensions
  new-from-patch: ""

severity:
  # Default value is empty string.
  # Set the default severity for issues. If severity rules are defined and the issues
  # do not match or no severity is provided to the rule this will be the default
  # severity applied. Severities should match the supported severity names of the
  # selected out format.
  # - Code: https://github.com/golangci/golangci-lint/blob/master/pkg/resultset/resultset.go#L15-L22
  # - linter: https://github.com/golangci/golangci-lint/blob/master/pkg/config/config.go#L144-L151
  default-severity: error

  # The default value is false.
  # If set to true severity-rules regular expressions are case sensitive.
  case-sensitive: false

  # The default value is empty list.
  # When a list of severity rules are provided, severity information will be added to lint
  # issues in JSON formats. Severity rules have the same filtering capability as exclude rules
  # except you are allowed to specify one matcher per severity rule and the only supported
  # matchers are 'path' and 'linters'.
  rules:
    - linters:
        - interface-check
      severity: error
      text: "Use 'any' instead of 'interface{}'"

    - linters:
        - gocritic
      severity: warning
      text: "Consider using modern Go practices"

    - linters:
        - revive
      severity: warning
      text: "Follow Go naming conventions"

# Skip directories
skip-dirs:
  - vendor
  - .git
  - node_modules
  - .vscode
  - .idea

# Skip files
skip-files:
  - ".*\\.pb\\.go$"
  - ".*\\.gen\\.go$"
  - ".*_mock\\.go$"
