run:
  timeout: 5m
  go: "1.21"

output:
  format: colored-line-number
  print-issued-line: true
  print-linter-name: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - dupl
        - goconst

linters:
  enable:
    - gofmt
    - goimports