run:
  timeout: 5m
  go: "1.21"

output:
  format: colored-line-number
  print-issued-line: true
  print-linter-name: true

linters-settings:
  errcheck:
    ignore: fmt:.*,[rR]ead.*,Close.*
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/arx-os/arxos/internal/domain.Logger).Log
          - (github.com/arx-os/arxos/internal/domain.Logger).Debug
          - (github.com/arx-os/arxos/internal/domain.Logger).Info
          - (github.com/arx-os/arxos/internal/domain.Logger).Warn
          - (github.com/arx-os/arxos/internal/domain.Logger).Error
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  unused:
    ignore: |
      ^test$
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentFormatting # breaks go: generate comments
      - whyNoLint        # linter directives are useful
  funlen:
    lines: 100
    statements: 50
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocyclo
        - dupl
        - goconst
    - path: cmd/
      linters:
        - gocyclo
    - path: internal/test/
      linters:
        - staticcheck
        - unused
        - interfacebloat

linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - gochecknoglobal
    - gochecknoinits
    - gocyclop
    - godot
    - godox
    - gomodguard
    - gofmt
    - gofumpt
    - goimports
    - golint
    - goprintffuncname
    - interfacer
    - maligned
    - nlreturn
    - noctx
    - nosnakecase
    - testpackage
    - unparam
    - unused
    - wsl
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errname
    - exhaustivestruct
    - exportloopref
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace