# Mockery Configuration for ArxOS
# Documentation: https://vektra.github.io/mockery/

# mockery version: v2.x
# Install: go install github.com/vektra/mockery/v2@latest

with-expecter: true
dir: "internal/mocks"
output: "{{.InterfaceDir}}/{{.PackageName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
inpackage: false
testonly: false
exported: true
keeptree: false

packages:
  # Domain repository interfaces
  github.com/arx-os/arxos/internal/domain:
    config:
      with-expecter: true
      dir: "internal/mocks/domain"
    interfaces:
      BuildingRepository:
      FloorRepository:
      RoomRepository:
      EquipmentRepository:
      UserRepository:
      OrganizationRepository:
      Logger:

  # BAS domain interfaces
  github.com/arx-os/arxos/internal/domain/bas:
    config:
      with-expecter: true
      dir: "internal/mocks/bas"
    interfaces:
      BASPointRepository:
      BASSystemRepository:

  # Version control interfaces (when ready)
  # github.com/arx-os/arxos/internal/domain/versioncontrol:
  #   config:
  #     with-expecter: true
  #     dir: "internal/mocks/versioncontrol"
  #   interfaces:
  #     BranchRepository:
  #     CommitRepository:

