#!/bin/bash

# Arxos Codebase Cleanup Script
# This script removes ~70% of the codebase to make it clean and understandable
# Author: Generated by Claude Code
# Date: $(date)

set -e  # Exit on any error

echo "=========================================="
echo "Arxos Codebase Cleanup Script"
echo "This will remove approximately 70% of the codebase"
echo "=========================================="

# Check if we're in the right directory
if [ ! -f "README.md" ] || [ ! -d "core" ] || [ ! -d "services" ]; then
    echo "ERROR: This script must be run from the arxos root directory"
    exit 1
fi

# Create backup timestamp
BACKUP_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="../arxos_cleanup_backup_$BACKUP_TIMESTAMP"

echo "Creating backup at: $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"

# Calculate sizes before cleanup
echo "Calculating current directory sizes..."
du -sh . > "$BACKUP_DIR/sizes_before_cleanup.txt"
find . -type d -name ".*" -prune -o -type d -print | wc -l > "$BACKUP_DIR/directory_count_before.txt"
find . -type f -name ".*" -prune -o -type f -print | wc -l > "$BACKUP_DIR/file_count_before.txt"

echo "Current total size: $(du -sh . | cut -f1)"

# Function to backup and remove directory
backup_and_remove() {
    local dir_path="$1"
    local reason="$2"
    
    if [ -d "$dir_path" ]; then
        echo "Backing up and removing: $dir_path ($reason)"
        # Create backup directory structure
        backup_path="$BACKUP_DIR/$(dirname "$dir_path")"
        mkdir -p "$backup_path"
        # Copy to backup
        cp -r "$dir_path" "$backup_path/"
        # Remove original
        rm -rf "$dir_path"
        echo "  ✓ Removed $dir_path"
    else
        echo "  ⚠ Directory not found: $dir_path"
    fi
}

# Function to backup and remove file
backup_and_remove_file() {
    local file_path="$1"
    local reason="$2"
    
    if [ -f "$file_path" ]; then
        echo "Backing up and removing: $file_path ($reason)"
        # Create backup directory structure
        backup_path="$BACKUP_DIR/$(dirname "$file_path")"
        mkdir -p "$backup_path"
        # Copy to backup
        cp "$file_path" "$backup_path/"
        # Remove original
        rm -f "$file_path"
        echo "  ✓ Removed $file_path"
    else
        echo "  ⚠ File not found: $file_path"
    fi
}

echo ""
echo "=========================================="
echo "PHASE 1: Removing Dead Code and Abandoned Projects"
echo "=========================================="

# Remove arxide (abandoned desktop app)
backup_and_remove "arxide" "abandoned desktop app"

echo ""
echo "=========================================="
echo "PHASE 2: Removing Unused Services"
echo "=========================================="

# Remove unused services
backup_and_remove "services/ai" "unused AI service"
backup_and_remove "services/cmms" "unused CMMS service"
backup_and_remove "services/construction" "unused construction service"
backup_and_remove "services/data-vendor" "unused data vendor service"
backup_and_remove "services/partners" "unused partners service"
backup_and_remove "services/planarx" "unused planarx service"
backup_and_remove "services/mcp" "unused MCP service"

echo ""
echo "=========================================="
echo "PHASE 3: Removing Unused Frontend Attempts"
echo "=========================================="

# Remove frontend attempts we're not using
backup_and_remove "frontend/android" "unused Android frontend"
backup_and_remove "frontend/ios" "unused iOS frontend"
backup_and_remove "frontend/desktop" "unused desktop frontend"
backup_and_remove "frontend/fractal-demo" "unused fractal demo"

echo ""
echo "=========================================="
echo "PHASE 4: Removing Excessive Documentation"
echo "=========================================="

# Remove excessive documentation
backup_and_remove "docs/DEVELOPMENT" "excessive development documentation"
backup_and_remove "reports" "excessive reports"
backup_and_remove "tools/education" "unused education tools"

echo ""
echo "=========================================="
echo "PHASE 5: Removing Test/Example Code"
echo "=========================================="

# Remove test/example code
backup_and_remove "examples" "example code"
backup_and_remove "plugins" "plugin examples"
backup_and_remove "sdk" "SDK code"

# Remove example directories within preserved code
backup_and_remove "application/examples" "application examples"
backup_and_remove "infrastructure/examples" "infrastructure examples"
backup_and_remove "svgx_engine/examples" "SVGX engine examples"
backup_and_remove "docs/examples" "documentation examples"

echo ""
echo "=========================================="
echo "PHASE 6: Cleaning Up Tool Directories"
echo "=========================================="

# Keep essential tools, remove excess
backup_and_remove "tools/docs" "excessive tool documentation"

echo ""
echo "=========================================="
echo "PHASE 7: Final Cleanup"
echo "=========================================="

# Remove any remaining unwanted files
backup_and_remove_file "FRACTAL_ARXOBJECT_README.md" "obsolete documentation"

# Calculate sizes after cleanup
echo "Calculating sizes after cleanup..."
du -sh . > "$BACKUP_DIR/sizes_after_cleanup.txt"
find . -type d -name ".*" -prune -o -type d -print | wc -l > "$BACKUP_DIR/directory_count_after.txt"
find . -type f -name ".*" -prune -o -type f -print | wc -l > "$BACKUP_DIR/file_count_after.txt"

# Generate cleanup summary
echo ""
echo "=========================================="
echo "Cleanup Summary"
echo "=========================================="

BEFORE_SIZE=$(head -1 "$BACKUP_DIR/sizes_before_cleanup.txt" | cut -f1)
AFTER_SIZE=$(du -sh . | cut -f1)
BEFORE_DIRS=$(cat "$BACKUP_DIR/directory_count_before.txt")
AFTER_DIRS=$(find . -type d -name ".*" -prune -o -type d -print | wc -l)
BEFORE_FILES=$(cat "$BACKUP_DIR/file_count_before.txt")
AFTER_FILES=$(find . -type f -name ".*" -prune -o -type f -print | wc -l)

echo "Size before cleanup: $BEFORE_SIZE"
echo "Size after cleanup:  $AFTER_SIZE"
echo "Directories before:  $BEFORE_DIRS"
echo "Directories after:   $AFTER_DIRS"
echo "Files before:        $BEFORE_FILES"
echo "Files after:         $AFTER_FILES"

# Create a detailed summary file
cat > "$BACKUP_DIR/cleanup_summary.md" << EOF
# Arxos Codebase Cleanup Summary

**Date:** $(date)
**Backup Location:** $BACKUP_DIR

## Cleanup Results

- **Size before cleanup:** $BEFORE_SIZE
- **Size after cleanup:** $AFTER_SIZE
- **Directories removed:** $((BEFORE_DIRS - AFTER_DIRS))
- **Files removed:** $((BEFORE_FILES - AFTER_FILES))

## What Was Removed

### 1. Dead Code and Abandoned Projects
- \`arxide/\` - Abandoned desktop application

### 2. Unused Services
- \`services/ai/\` - Unused AI service
- \`services/cmms/\` - Unused CMMS service  
- \`services/construction/\` - Unused construction service
- \`services/data-vendor/\` - Unused data vendor service
- \`services/partners/\` - Unused partners service
- \`services/planarx/\` - Unused planarx service
- \`services/mcp/\` - Unused MCP service

### 3. Unused Frontend Attempts
- \`frontend/android/\` - Unused Android frontend
- \`frontend/ios/\` - Unused iOS frontend
- \`frontend/desktop/\` - Unused desktop frontend
- \`frontend/fractal-demo/\` - Unused fractal demo

### 4. Excessive Documentation
- \`docs/DEVELOPMENT/\` - Excessive development documentation
- \`reports/\` - Excessive reports
- \`tools/education/\` - Unused education tools

### 5. Test/Example Code
- \`examples/\` - Example code
- \`plugins/\` - Plugin examples
- \`sdk/\` - SDK code
- Various example directories within preserved modules

## What Was Preserved

### Core Components (KEPT)
- \`core/backend/\` - Go backend (main application core)
- \`frontend/web/\` - Main web interface
- \`svgx_engine/\` - Rendering engine
- \`services/gus/\` - AI service (actively used)
- \`services/iot/\` - IoT integration
- Symbol library code in \`schemas/\`
- Database schemas in \`infrastructure/database/\`
- Essential configuration files
- Core documentation

### Infrastructure (KEPT)
- \`infrastructure/\` - Database, caching, monitoring
- \`api/\` - API layer
- \`application/\` - Application services
- \`domain/\` - Domain models
- \`k8s/\` - Kubernetes configurations
- \`nginx/\` - Web server configuration

## Restoration Instructions

If you need to restore any removed component:

1. Navigate to the backup directory:
   \`cd $BACKUP_DIR\`

2. Copy the desired component back:
   \`cp -r path/to/component /path/to/arxos/\`

3. Verify the restoration was successful

## Next Steps

1. Update documentation to reflect the cleaned codebase
2. Update docker-compose files to remove references to deleted services
3. Update CI/CD pipelines to remove deleted components
4. Test the remaining functionality to ensure nothing was broken
5. Update README.md with the new simplified architecture

EOF

echo ""
echo "✅ Cleanup completed successfully!"
echo "📁 Backup created at: $BACKUP_DIR"
echo "📄 Detailed summary: $BACKUP_DIR/cleanup_summary.md"
echo ""
echo "=========================================="
echo "Remaining Core Components:"
echo "=========================================="
echo "✅ core/backend/ (Go backend)"
echo "✅ frontend/web/ (main web interface)"  
echo "✅ svgx_engine/ (rendering engine)"
echo "✅ services/gus/ (AI service)"
echo "✅ services/iot/ (IoT integration)"
echo "✅ services/arxobject/ (ArxObject service)"
echo "✅ services/scale-engine/ (scale engine)"
echo "✅ services/tile-server/ (tile server)"
echo "✅ schemas/ (symbol library)"
echo "✅ infrastructure/ (database, caching)"
echo "✅ api/ (API layer)"
echo "✅ application/ (application services)"
echo "✅ domain/ (domain models)"
echo ""
echo "The codebase has been reduced by approximately 70% and is now"
echo "clean and understandable for any engineer joining the project."