// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://arxos.io/terms",
        "contact": {
            "name": "ArxOS Support",
            "url": "https://arxos.io/support",
            "email": "support@arxos.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user and receive access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docs.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully authenticated",
                        "schema": {
                            "$ref": "#/definitions/docs.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidate the current session",
                "tags": [
                    "Authentication"
                ],
                "summary": "User Logout",
                "responses": {
                    "204": {
                        "description": "Successfully logged out"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refresh access token using refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Refresh Token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "refresh",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docs.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New tokens generated",
                        "schema": {
                            "$ref": "#/definitions/docs.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid refresh token",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/buildings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of buildings accessible to the user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buildings"
                ],
                "summary": "List Buildings",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Limit number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/docs.BuildingResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new building",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buildings"
                ],
                "summary": "Create Building",
                "parameters": [
                    {
                        "description": "Building details",
                        "name": "building",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docs.CreateBuildingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Building created",
                        "schema": {
                            "$ref": "#/definitions/docs.BuildingResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/buildings/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detailed information about a specific building",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buildings"
                ],
                "summary": "Get Building",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Building ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.BuildingResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Building not found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing building",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Buildings"
                ],
                "summary": "Update Building",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Building ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Building updates",
                        "name": "building",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docs.UpdateBuildingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Building updated",
                        "schema": {
                            "$ref": "#/definitions/docs.BuildingResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Building not found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a building",
                "tags": [
                    "Buildings"
                ],
                "summary": "Delete Building",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Building ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Building deleted"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Building not found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/equipment": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get equipment for a building",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment"
                ],
                "summary": "List Equipment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Building ID",
                        "name": "building_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Equipment type filter",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Equipment status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Room ID filter",
                        "name": "room_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/docs.EquipmentResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/equipment/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detailed information about specific equipment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipment"
                ],
                "summary": "Get Equipment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Equipment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.EquipmentResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Equipment not found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is healthy and responsive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "API is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Search across buildings, equipment, and rooms",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Search",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by type (building, equipment, room)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Limit results",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid query",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get information about the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get Current User",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the authenticated user's information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update Current User",
                "parameters": [
                    {
                        "description": "User updates",
                        "name": "updates",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docs.UserUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me/password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change the current user's password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Change Password",
                "parameters": [
                    {
                        "description": "Password change request",
                        "name": "passwords",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/docs.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Password changed successfully"
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized or invalid old password",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "docs.AuthResponse": {
            "description": "Authentication response with JWT tokens",
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "JWT access token",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "expires_in": {
                    "description": "Token expiration time in seconds",
                    "type": "integer",
                    "example": 3600
                },
                "refresh_token": {
                    "description": "JWT refresh token",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "token_type": {
                    "description": "Token type",
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "docs.BuildingResponse": {
            "description": "Building information with metadata",
            "type": "object",
            "properties": {
                "address": {
                    "description": "Building address",
                    "type": "string",
                    "example": "123 Main St, City, State 12345"
                },
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2024-01-15T09:30:00Z"
                },
                "description": {
                    "description": "Building description",
                    "type": "string",
                    "example": "5-story office building with parking garage"
                },
                "floors": {
                    "description": "Number of floors",
                    "type": "integer",
                    "example": 5
                },
                "id": {
                    "description": "Building ID",
                    "type": "string",
                    "example": "bldg-123456"
                },
                "metadata": {
                    "description": "Building metadata",
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "description": "Building name",
                    "type": "string",
                    "example": "Main Office Building"
                },
                "organization_id": {
                    "description": "Organization ID",
                    "type": "string",
                    "example": "org-789012"
                },
                "total_area": {
                    "description": "Total area in square meters",
                    "type": "number",
                    "example": 10000.5
                },
                "updated_at": {
                    "description": "Last update timestamp",
                    "type": "string",
                    "example": "2024-01-20T14:45:00Z"
                }
            }
        },
        "docs.ChangePasswordRequest": {
            "description": "Request to change user password",
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "description": "New password (min 8 characters)",
                    "type": "string",
                    "minLength": 8,
                    "example": "newsecurepassword456"
                },
                "old_password": {
                    "description": "Current password",
                    "type": "string",
                    "example": "oldpassword123"
                }
            }
        },
        "docs.CreateBuildingRequest": {
            "description": "Building information for creation",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "address": {
                    "description": "Building address",
                    "type": "string",
                    "example": "123 Main St"
                },
                "building_type": {
                    "description": "Building type",
                    "type": "string",
                    "example": "office"
                },
                "city": {
                    "description": "City",
                    "type": "string",
                    "example": "New York"
                },
                "country": {
                    "description": "Country",
                    "type": "string",
                    "example": "USA"
                },
                "floors": {
                    "description": "Number of floors",
                    "type": "integer",
                    "example": 5
                },
                "name": {
                    "description": "Building name",
                    "type": "string",
                    "example": "Main Office Building"
                },
                "postal_code": {
                    "description": "Postal code",
                    "type": "string",
                    "example": "10001"
                },
                "state": {
                    "description": "State or province",
                    "type": "string",
                    "example": "NY"
                },
                "total_area": {
                    "description": "Total area in square meters",
                    "type": "number",
                    "example": 10000.5
                }
            }
        },
        "docs.EquipmentResponse": {
            "description": "Equipment information with metadata",
            "type": "object",
            "properties": {
                "building_id": {
                    "description": "Building ID",
                    "type": "string",
                    "example": "bldg-123456"
                },
                "created_at": {
                    "description": "Creation timestamp",
                    "type": "string",
                    "example": "2024-01-15T09:30:00Z"
                },
                "id": {
                    "description": "Equipment ID",
                    "type": "string",
                    "example": "equip-987654"
                },
                "installation_date": {
                    "description": "Installation date",
                    "type": "string",
                    "example": "2023-06-15T00:00:00Z"
                },
                "metadata": {
                    "description": "Equipment metadata",
                    "type": "object",
                    "additionalProperties": true
                },
                "model": {
                    "description": "Equipment model",
                    "type": "string",
                    "example": "Carrier 38VRF"
                },
                "name": {
                    "description": "Equipment name",
                    "type": "string",
                    "example": "HVAC Unit 1"
                },
                "room_id": {
                    "description": "Room ID where equipment is located",
                    "type": "string",
                    "example": "room-456"
                },
                "serial_number": {
                    "description": "Serial number",
                    "type": "string",
                    "example": "SN-123456789"
                },
                "status": {
                    "description": "Equipment status",
                    "type": "string",
                    "example": "operational"
                },
                "type": {
                    "description": "Equipment type",
                    "type": "string",
                    "example": "hvac"
                },
                "updated_at": {
                    "description": "Last update timestamp",
                    "type": "string",
                    "example": "2024-01-20T14:45:00Z"
                }
            }
        },
        "docs.ErrorResponse": {
            "description": "Standard error response",
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error code",
                    "type": "string",
                    "example": "VALIDATION_ERROR"
                },
                "details": {
                    "description": "Detailed error information",
                    "type": "object",
                    "additionalProperties": true
                },
                "message": {
                    "description": "Error message",
                    "type": "string",
                    "example": "Invalid input data"
                },
                "request_id": {
                    "description": "Request ID for tracking",
                    "type": "string",
                    "example": "req-123456789"
                }
            }
        },
        "docs.LoginRequest": {
            "description": "User login credentials",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "Email address of the user\n@example user@example.com",
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "description": "User password\n@example securepassword123",
                    "type": "string",
                    "example": "securepassword123"
                }
            }
        },
        "docs.RefreshRequest": {
            "description": "Request to refresh access token",
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "description": "Refresh token",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                }
            }
        },
        "docs.SearchResponse": {
            "description": "Search results with pagination info",
            "type": "object",
            "properties": {
                "limit": {
                    "description": "Current limit",
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "description": "Current offset",
                    "type": "integer",
                    "example": 0
                },
                "query": {
                    "description": "Search query",
                    "type": "string",
                    "example": "conference room"
                },
                "results": {
                    "description": "Search results",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docs.SearchResult"
                    }
                },
                "total": {
                    "description": "Total number of results",
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "docs.SearchResult": {
            "description": "Individual search result",
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description or summary",
                    "type": "string",
                    "example": "Large conference room on 3rd floor"
                },
                "id": {
                    "description": "Result ID",
                    "type": "string",
                    "example": "room-456"
                },
                "metadata": {
                    "description": "Additional metadata",
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "description": "Display name",
                    "type": "string",
                    "example": "Conference Room A"
                },
                "score": {
                    "description": "Relevance score",
                    "type": "number",
                    "example": 0.95
                },
                "type": {
                    "description": "Entity type",
                    "type": "string",
                    "example": "room"
                }
            }
        },
        "docs.UpdateBuildingRequest": {
            "description": "Building information for updates (all fields optional)",
            "type": "object",
            "properties": {
                "address": {
                    "description": "Building address",
                    "type": "string",
                    "example": "456 New St"
                },
                "building_type": {
                    "description": "Building type",
                    "type": "string",
                    "example": "mixed-use"
                },
                "city": {
                    "description": "City",
                    "type": "string",
                    "example": "Los Angeles"
                },
                "country": {
                    "description": "Country",
                    "type": "string",
                    "example": "USA"
                },
                "floors": {
                    "description": "Number of floors",
                    "type": "integer",
                    "example": 6
                },
                "name": {
                    "description": "Building name",
                    "type": "string",
                    "example": "Updated Building Name"
                },
                "postal_code": {
                    "description": "Postal code",
                    "type": "string",
                    "example": "90001"
                },
                "state": {
                    "description": "State or province",
                    "type": "string",
                    "example": "CA"
                },
                "total_area": {
                    "description": "Total area in square meters",
                    "type": "number",
                    "example": 12000.5
                }
            }
        },
        "docs.UserResponse": {
            "description": "User profile information",
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Account creation date",
                    "type": "string",
                    "example": "2024-01-15T09:30:00Z"
                },
                "email": {
                    "description": "User email",
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "description": "User ID",
                    "type": "string",
                    "example": "user-123456"
                },
                "name": {
                    "description": "User's full name",
                    "type": "string",
                    "example": "John Doe"
                },
                "organization_id": {
                    "description": "Organization ID",
                    "type": "string",
                    "example": "org-789012"
                },
                "preferences": {
                    "description": "User preferences",
                    "type": "object",
                    "additionalProperties": true
                },
                "role": {
                    "description": "User role",
                    "type": "string",
                    "example": "admin"
                },
                "updated_at": {
                    "description": "Last update date",
                    "type": "string",
                    "example": "2024-01-20T14:45:00Z"
                }
            }
        },
        "docs.UserUpdateRequest": {
            "description": "User profile update request",
            "type": "object",
            "properties": {
                "name": {
                    "description": "User's full name",
                    "type": "string",
                    "example": "Jane Doe"
                },
                "phone": {
                    "description": "User's phone number",
                    "type": "string",
                    "example": "+1-555-123-4567"
                },
                "preferences": {
                    "description": "User preferences",
                    "type": "object",
                    "additionalProperties": true
                },
                "timezone": {
                    "description": "User's timezone",
                    "type": "string",
                    "example": "America/New_York"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ArxOS Building Intelligence API",
	Description:      "REST API for ArxOS Building Information Management System",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
