# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'ArxOSMobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArxOSMobile
  # Add any additional dependencies here
  
  # ARKit and RealityKit are included in iOS SDK
  # No additional pods needed for basic AR functionality
  
  target 'ArxOSMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArxOSMobileUITests' do
    # Pods for testing
  end

end
