#!/bin/bash

# Script to renumber migrations sequentially
cd /Users/joelpate/repos/arxos/core/migrations

# Rename files to new sequential numbers
mv 001_create_arx_schema.sql 001_create_arx_schema.sql
mv 009_create_security_tables.sql 002_create_security_tables.sql
mv 011_seed_industry_benchmarks_and_sample_data.sql 003_seed_sample_data.sql
mv 012_database_performance_optimization.sql 004_database_performance_optimization.sql
mv 019_add_performance_indexes.sql 005_add_performance_indexes.sql
mv 021_upgrade_arxobjects_nanometer_precision.sql 006_upgrade_arxobjects_nanometer_precision.sql
mv 022_arxobjects_nanometer_precision.sql 007_arxobjects_nanometer_precision.sql
mv 023_user_management_enhancement.sql 008_user_management_enhancement.sql
mv 024_create_cache_tables.sql 009_create_cache_tables.sql
mv 025_create_arxobjects_spatial.sql 010_create_arxobjects_spatial.sql
mv 100_create_arxobjects_table.sql 011_create_arxobjects_table.sql
mv 200_building_states.sql 012_building_states.sql
mv 201_deployments.sql 013_deployments.sql
mv 202_gitops_features.sql 014_gitops_features.sql

echo "Migrations renumbered successfully"
ls -1 *.sql