#!/bin/bash
# Setup Cargo configuration for Android cross-compilation
# This script generates ~/.cargo/config.toml with Android linker configuration

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔧 Setting up Cargo configuration for Android...${NC}"

# Check for Android NDK
NDK_PATH="${ANDROID_NDK_HOME:-$HOME/Android/Sdk/ndk-bundle}"

if [ ! -d "$NDK_PATH" ]; then
    echo -e "${YELLOW}⚠️  Android NDK not found at $NDK_PATH${NC}"
    echo "Please set ANDROID_NDK_HOME environment variable"
    echo "Example: export ANDROID_NDK_HOME=/path/to/android-ndk"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Detect NDK toolchain path
if [ -d "$NDK_PATH/toolchains/llvm/prebuilt" ]; then
    # Find the prebuilt directory (could be linux-x86_64, darwin-x86_64, etc.)
    PREBUILT_DIR=$(find "$NDK_PATH/toolchains/llvm/prebuilt" -mindepth 1 -maxdepth 1 -type d | head -1)
    if [ -n "$PREBUILT_DIR" ]; then
        NDK_TOOLCHAIN="$PREBUILT_DIR"
    else
        echo -e "${RED}❌ Could not find NDK toolchain directory${NC}"
        exit 1
    fi
else
    echo -e "${YELLOW}⚠️  Could not find NDK toolchain at $NDK_PATH/toolchains/llvm/prebuilt${NC}"
    echo "Using default paths. You may need to adjust manually."
    NDK_TOOLCHAIN="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64"
fi

# Detect platform
if [[ "$OSTYPE" == "darwin"* ]]; then
    PREBUILT_PLATFORM="darwin-x86_64"
    if [[ $(uname -m) == "arm64" ]]; then
        PREBUILT_PLATFORM="darwin-arm64"
    fi
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    PREBUILT_PLATFORM="linux-x86_64"
else
    PREBUILT_PLATFORM="linux-x86_64"  # Default
fi

# Try to find actual prebuilt directory
if [ -d "$NDK_PATH/toolchains/llvm/prebuilt/$PREBUILT_PLATFORM" ]; then
    NDK_TOOLCHAIN="$NDK_PATH/toolchains/llvm/prebuilt/$PREBUILT_PLATFORM"
elif [ -d "$NDK_PATH/toolchains/llvm/prebuilt" ]; then
    # Find any prebuilt directory
    NDK_TOOLCHAIN=$(find "$NDK_PATH/toolchains/llvm/prebuilt" -mindepth 1 -maxdepth 1 -type d | head -1)
else
    echo -e "${RED}❌ Could not find NDK toolchain directory${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Using NDK toolchain at: $NDK_TOOLCHAIN${NC}"

# Create Cargo config directory if it doesn't exist
CARGO_CONFIG_DIR="$HOME/.cargo"
CARGO_CONFIG_FILE="$CARGO_CONFIG_DIR/config.toml"

mkdir -p "$CARGO_CONFIG_DIR"

# Backup existing config if it exists
if [ -f "$CARGO_CONFIG_FILE" ]; then
    BACKUP_FILE="${CARGO_CONFIG_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    cp "$CARGO_CONFIG_FILE" "$BACKUP_FILE"
    echo -e "${BLUE}📦 Backed up existing config to: $BACKUP_FILE${NC}"
fi

# Android API level (minimum supported)
API_LEVEL="${ANDROID_API_LEVEL:-21}"

# Generate Cargo config
echo -e "${BLUE}📝 Generating Cargo configuration...${NC}"

cat >> "$CARGO_CONFIG_FILE" << EOF

# ArxOS Android cross-compilation configuration
# Generated by scripts/setup-android-cargo.sh on $(date)

[target.aarch64-linux-android]
ar = "$NDK_TOOLCHAIN/bin/llvm-ar"
linker = "$NDK_TOOLCHAIN/bin/aarch64-linux-android${API_LEVEL}-clang"

[target.armv7-linux-androideabi]
ar = "$NDK_TOOLCHAIN/bin/llvm-ar"
linker = "$NDK_TOOLCHAIN/bin/armv7a-linux-androideabi${API_LEVEL}-clang"

[target.i686-linux-android]
ar = "$NDK_TOOLCHAIN/bin/llvm-ar"
linker = "$NDK_TOOLCHAIN/bin/i686-linux-android${API_LEVEL}-clang"

[target.x86_64-linux-android]
ar = "$NDK_TOOLCHAIN/bin/llvm-ar"
linker = "$NDK_TOOLCHAIN/bin/x86_64-linux-android${API_LEVEL}-clang"

EOF

echo -e "${GREEN}✅ Cargo configuration updated!${NC}"
echo ""
echo "📋 Configuration written to: $CARGO_CONFIG_FILE"
echo ""
echo "You can now build for Android using:"
echo "  ./scripts/build-mobile-android.sh"
echo ""
echo "To use a different Android API level, set ANDROID_API_LEVEL:"
echo "  export ANDROID_API_LEVEL=23"
echo "  ./scripts/setup-android-cargo.sh"

