#!/bin/bash

# ArxOS Development Database Setup Script
# This script sets up a local PostgreSQL database with PostGIS for ArxOS development

set -e  # Exit on error

# Colors for output
GREEN='\033[0.32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
DB_NAME="${ARXOS_DB_NAME:-arxos_dev}"
DB_USER="${ARXOS_DB_USER:-$(whoami)}"
DB_HOST="${ARXOS_DB_HOST:-localhost}"
DB_PORT="${ARXOS_DB_PORT:-5432}"

echo "============================================"
echo "ArxOS Development Database Setup"
echo "============================================"
echo ""
echo "Configuration:"
echo "  Database: $DB_NAME"
echo "  User:     $DB_USER"
echo "  Host:     $DB_HOST"
echo "  Port:     $DB_PORT"
echo ""

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    echo -e "${RED}Error: PostgreSQL is not installed${NC}"
    echo ""
    echo "Install PostgreSQL:"
    echo "  macOS:   brew install postgresql@14 postgis"
    echo "  Ubuntu:  sudo apt-get install postgresql-14 postgresql-14-postgis-3"
    echo "  Docker:  docker run -p 5432:5432 -e POSTGRES_PASSWORD=arxos postgis/postgis:14-3.3"
    exit 1
fi

# Check if PostgreSQL is running
if ! pg_isready -h $DB_HOST -p $DB_PORT &> /dev/null; then
    echo -e "${RED}Error: PostgreSQL is not running on $DB_HOST:$DB_PORT${NC}"
    echo ""
    echo "Start PostgreSQL:"
    echo "  macOS:   brew services start postgresql@14"
    echo "  Ubuntu:  sudo systemctl start postgresql"
    echo "  Docker:  docker start <container>"
    exit 1
fi

echo -e "${GREEN}✓${NC} PostgreSQL is running"

# Check if database already exists
if psql -h $DB_HOST -p $DB_PORT -U $DB_USER -lqt | cut -d \| -f 1 | grep -qw $DB_NAME; then
    echo ""
    echo -e "${YELLOW}Warning: Database '$DB_NAME' already exists${NC}"
    read -p "Drop and recreate? (y/N): " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Dropping existing database..."
        dropdb -h $DB_HOST -p $DB_PORT -U $DB_USER $DB_NAME
        echo -e "${GREEN}✓${NC} Database dropped"
    else
        echo "Keeping existing database"
        exit 0
    fi
fi

# Create database
echo ""
echo "Creating database '$DB_NAME'..."
createdb -h $DB_HOST -p $DB_PORT -U $DB_USER $DB_NAME
echo -e "${GREEN}✓${NC} Database created"

# Enable PostGIS extension
echo ""
echo "Enabling PostGIS extension..."
psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -c "CREATE EXTENSION IF NOT EXISTS postgis;"
psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -c "CREATE EXTENSION IF NOT EXISTS postgis_topology;"
echo -e "${GREEN}✓${NC} PostGIS extension enabled"

# Verify PostGIS
POSTGIS_VERSION=$(psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -t -c "SELECT PostGIS_Version();" | xargs)
echo -e "${GREEN}✓${NC} PostGIS version: $POSTGIS_VERSION"

# Create .env file if it doesn't exist
ENV_FILE=".env"
if [ ! -f "$ENV_FILE" ]; then
    echo ""
    echo "Creating .env file..."
    cat > $ENV_FILE <<EOF
# ArxOS Development Environment Configuration
# Generated by setup-dev-database.sh

# Database Configuration
DATABASE_URL=postgres://$DB_USER@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable
POSTGIS_HOST=$DB_HOST
POSTGIS_PORT=$DB_PORT
POSTGIS_DATABASE=$DB_NAME
POSTGIS_USER=$DB_USER
POSTGIS_SSLMODE=disable

# Application Configuration
ARXOS_MODE=development
LOG_LEVEL=debug

# IFC Service (optional)
IFC_SERVICE_URL=http://localhost:5000
IFC_SERVICE_ENABLED=false

# Cache Configuration
CACHE_ENABLED=true
REDIS_URL=redis://localhost:6379

EOF
    echo -e "${GREEN}✓${NC} Created .env file"
else
    echo ""
    echo -e "${YELLOW}Note: .env file already exists, not overwriting${NC}"
fi

echo ""
echo "============================================"
echo -e "${GREEN}Setup Complete!${NC}"
echo "============================================"
echo ""
echo "Next steps:"
echo ""
echo "1. Update your config file (configs/environments/development.yml):"
echo "   postgis:"
echo "     host: $DB_HOST"
echo "     port: $DB_PORT"
echo "     database: $DB_NAME"
echo "     user: $DB_USER"
echo "     sslmode: disable"
echo ""
echo "2. Run migrations:"
echo "   cd $(pwd)"
echo "   go run cmd/arx/main.go migrate up"
echo ""
echo "3. Verify setup:"
echo "   go run cmd/arx/main.go health"
echo ""
echo "4. Test building creation:"
echo "   go run cmd/arx/main.go building create --name \"Test School\" --address \"123 Main St\""
echo ""
echo "Database connection string:"
echo "   postgres://$DB_USER@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable"
echo ""
echo -e "${YELLOW}Pro tip:${NC} Add this to your shell profile for easy access:"
echo "   export DATABASE_URL=\"postgres://$DB_USER@$DB_HOST:$DB_PORT/$DB_NAME?sslmode=disable\""
echo ""

