/*!
 * @file arxos_mobile.h
 * @brief C FFI bindings for ArxOS mobile integration
 * 
 * This header provides C-compatible function exports for iOS and Android.
 * Functions return JSON strings that must be freed by the caller using arxos_free_string().
 * 
 * @note This file is auto-generated by cbindgen from src/mobile_ffi/ffi.rs
 * @warning DO NOT EDIT THIS FILE MANUALLY - Changes will be overwritten
 * @see src/mobile_ffi/ffi.rs for the source implementation
 */

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#ifdef __cplusplus
extern "C" {
#endif



#ifndef ARXOS_MOBILE_H
#define ARXOS_MOBILE_H



#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

char *arxos_economy_snapshot(const char *address);

char *arxos_economy_stake(const char *amount);

char *arxos_economy_unstake(const char *amount);

char *arxos_economy_claim(void);

/**
 * Load a PR for review (game mode)
 *
 * Returns JSON with PR summary including validation results
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `pr_id` is a valid null-terminated C string or null
 * - `pr_dir` is a valid null-terminated C string or null
 * - `building_name` is a valid null-terminated C string or null
 */
char *arxos_load_pr(const char *pr_id, const char *pr_dir, const char *building_name);

/**
 * Validate equipment placement against constraints
 *
 * Returns JSON validation result with violations and suggestions
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `equipment_json` is a valid null-terminated C string or null
 * - `constraints_json` is a valid null-terminated C string or null
 */
char *arxos_validate_constraints(const char *equipment_json, const char *constraints_json);

/**
 * Get game plan from planning session
 *
 * Returns JSON with plan data, placements, and validation summary
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `session_id` is a valid null-terminated C string or null
 * - `building_name` is a valid null-terminated C string or null
 */
char *arxos_get_game_plan(const char *session_id, const char *building_name);

/**
 * Free a C string allocated by ArxOS
 *
 * # Safety
 * This function must only be called with pointers returned from ArxOS FFI functions
 */
void arxos_free_string(char *ptr);

/**
 * Get the last error code from the last operation
 */
int32_t arxos_last_error(void);

/**
 * Get the last error message
 */
char *arxos_last_error_message(void);

/**
 * List all rooms in a building
 *
 * # Safety
 * The building_name parameter must be a valid UTF-8 null-terminated string
 */
char *arxos_list_rooms(const char *building_name);

/**
 * Get a specific room by ID
 *
 * # Safety
 * The building_name and room_id parameters must be valid UTF-8 null-terminated strings
 */
char *arxos_get_room(const char *building_name, const char *room_id);

/**
 * List all equipment in a building
 *
 * # Safety
 * The building_name parameter must be a valid UTF-8 null-terminated string
 */
char *arxos_list_equipment(const char *building_name);

/**
 * Get a specific equipment item by ID
 *
 * # Safety
 * The building_name and equipment_id parameters must be valid UTF-8 null-terminated strings
 */
char *arxos_get_equipment(const char *building_name, const char *equipment_id);

/**
 * Parse AR scan data from JSON string
 *
 * Returns parsed AR scan data as JSON
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `json_data` is a valid null-terminated C string or null
 */
char *arxos_parse_ar_scan(const char *json_data);

/**
 * Process AR scan and extract equipment
 *
 * Returns equipment info list as JSON
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `json_data` is a valid null-terminated C string or null
 */
char *arxos_extract_equipment(const char *json_data);

/**
 * Process AR scan and create pending equipment items
 *
 * # Arguments
 * * `json_data` - JSON string of AR scan data from mobile
 * * `building_name` - Name of building for context
 * * `confidence_threshold` - Minimum confidence (0.0-1.0) to create pending items
 *
 * Returns JSON with pending equipment IDs and details
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `json_data` is a valid null-terminated C string or null
 * - `building_name` is a valid null-terminated C string or null
 */
char *arxos_process_ar_scan_to_pending(const char *json_data,
                                       const char *building_name,
                                       double confidence_threshold);

/**
 * Export building to AR-compatible format
 *
 * # Arguments
 * * `building_name` - Name of building to export
 * * `format` - Export format: "gltf" or "usdz"
 *
 * Returns JSON with export status and file path
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `building_name` is a valid null-terminated C string or null
 * - `format` is a valid null-terminated C string or null
 */
char *arxos_export_for_ar(const char *building_name, const char *format);

/**
 * Load/export building model for AR viewing
 *
 * This function exports a building to AR-compatible format (USDZ or glTF) and returns
 * the file path where the model was saved. If `output_path` is null, a temporary file
 * will be created in the system temp directory.
 *
 * # Arguments
 * * `building_name` - Name of building to export
 * * `format` - Export format: "usdz" or "gltf" (case-insensitive)
 * * `output_path` - Optional path where model should be saved (null for temp file)
 *
 * # Returns
 * JSON string with:
 * ```json
 * {
 *   "success": true,
 *   "building": "building_name",
 *   "format": "usdz",
 *   "file_path": "/path/to/model.usdz",
 *   "file_size": 12345,
 *   "message": "Model exported successfully"
 * }
 * ```
 *
 * # Safety
 * This function is FFI-safe and handles null pointers gracefully.
 */
char *arxos_load_ar_model(const char *building_name, const char *format, const char *output_path);

/**
 * Save AR scan data and process to pending equipment
 *
 * This function accepts AR scan data from mobile devices, optionally saves it to a file
 * for debugging/audit purposes, and processes it to create pending equipment items that
 * can be reviewed and confirmed by users.
 *
 * # Arguments
 * * `json_data` - JSON string containing AR scan data (see ARScanData structure)
 * * `building_name` - Name of building for context
 * * `confidence_threshold` - Minimum confidence score (0.0-1.0) to create pending items
 *
 * # Returns
 * JSON string with:
 * ```json
 * {
 *   "success": true,
 *   "building": "building_name",
 *   "pending_count": 3,
 *   "pending_ids": ["pending-1", "pending-2", "pending-3"],
 *   "confidence_threshold": 0.7,
 *   "scan_timestamp": "2025-11-03T14:30:00Z",
 *   "message": "AR scan processed successfully"
 * }
 * ```
 *
 * # Safety
 * This function is FFI-safe and handles null pointers gracefully.
 */
char *arxos_save_ar_scan(const char *json_data,
                         const char *building_name,
                         const char *user_email,
                         double confidence_threshold);

/**
 * List pending equipment for a building
 *
 * Returns all pending equipment items that need user confirmation.
 *
 * # Arguments
 * * `building_name` - Name of building
 *
 * # Returns
 * JSON string with pending equipment list
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `building_name` is a valid null-terminated C string or null
 */
char *arxos_list_pending_equipment(const char *building_name);

/**
 * Confirm pending equipment and add to building data
 *
 * Confirms a pending equipment item, adds it to the building data, and optionally commits to Git.
 *
 * # Arguments
 * * `building_name` - Name of building
 * * `pending_id` - ID of pending equipment to confirm
 * * `user_email` - User email from mobile app (can be null for backward compatibility)
 * * `commit_to_git` - Whether to commit changes to Git (1 = yes, 0 = no)
 *
 * # Returns
 * JSON string with confirmation result
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `building_name` is a valid null-terminated C string or null
 * - `pending_id` is a valid null-terminated C string or null
 * - `user_email` is a valid null-terminated C string or null
 */
char *arxos_confirm_pending_equipment(const char *building_name,
                                      const char *pending_id,
                                      const char *user_email,
                                      int32_t commit_to_git);

/**
 * Request user registration from mobile app
 *
 * Creates a pending user registration request that will be reviewed by an admin.
 *
 * # Arguments
 * * `building_name` - Name of building (repository)
 * * `email` - User's email address
 * * `name` - User's full name
 * * `organization` - Organization (optional, can be null)
 * * `role` - Role (optional, can be null)
 * * `phone` - Phone number (optional, can be null)
 * * `device_info` - Device information (optional, can be null)
 * * `app_version` - App version (optional, can be null)
 *
 * # Returns
 * JSON string with request result (includes request_id and status)
 *
 * # Safety
 * This function is FFI-safe and handles null pointers gracefully.
 */
char *arxos_request_user_registration(const char *building_name,
                                      const char *email,
                                      const char *name,
                                      const char *organization,
                                      const char *role,
                                      const char *phone,
                                      const char *device_info,
                                      const char *app_version);

/**
 * Check registration status for a mobile user
 *
 * Returns the current status of a user's registration request.
 *
 * # Arguments
 * * `building_name` - Name of building (repository)
 * * `email` - User's email address
 *
 * # Returns
 * JSON string with registration status (pending, approved, denied, registered, or not_found)
 *
 * # Safety
 * This function is FFI-safe and handles null pointers gracefully.
 */
char *arxos_check_registration_status(const char *building_name, const char *email);

/**
 * Check if GPG is available on the system
 *
 * Returns whether GPG is installed and available for use.
 *
 * # Returns
 * JSON string with availability status
 *
 * # Safety
 * This function is FFI-safe.
 */
char *arxos_check_gpg_available(void);

/**
 * Get GPG key fingerprint for a user's email
 *
 * Looks up the GPG key fingerprint associated with the given email address.
 *
 * # Arguments
 * * `email` - User's email address
 *
 * # Returns
 * JSON string with fingerprint or error
 *
 * # Safety
 * This function is FFI-safe and handles null pointers gracefully.
 */
char *arxos_get_gpg_fingerprint(const char *email);

/**
 * Configure Git signing key for a repository
 *
 * Sets the user.signingkey Git configuration for the building repository.
 *
 * # Arguments
 * * `building_name` - Name of building (repository)
 * * `key_id` - GPG key ID to use for signing
 *
 * # Returns
 * JSON string with configuration result
 *
 * # Safety
 * This function is FFI-safe and handles null pointers gracefully.
 */
char *arxos_configure_git_signing(const char *building_name, const char *key_id);

/**
 * Reject pending equipment
 *
 * Marks a pending equipment item as rejected without adding it to building data.
 *
 * # Arguments
 * * `building_name` - Name of building
 * * `pending_id` - ID of pending equipment to reject
 *
 * # Returns
 * JSON string with rejection result
 *
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers. The caller must ensure:
 * - `building_name` is a valid null-terminated C string or null
 * - `pending_id` is a valid null-terminated C string or null
 */
char *arxos_reject_pending_equipment(const char *building_name, const char *pending_id);

#endif  /* ARXOS_MOBILE_H */

#ifdef __cplusplus
}
#endif
